#!/usr/bin/env python3
"""04_qa.py - quality report and the stats file every document reads its numbers from.

Outputs: data/processed/qa_report.txt, paper/stats.json. Exits non-zero if a hard check fails.
"""
import json, os, sys
import numpy as np, pandas as pd, openpyxl
import ahcp_load as L

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
P = os.path.join(ROOT, "data", "processed"); I = os.path.join(ROOT, "data", "interim")
bc = json.load(open(os.path.join(I, "build_counts.json"))); lc = json.load(open(os.path.join(I, "link_counts.json")))
insp = pd.read_csv(os.path.join(P, "ahcp_inspections.csv.gz"), dtype={"inspection_id": str, "property_id": str}, parse_dates=["inspection_date"])
prop = pd.read_csv(os.path.join(P, "ahcp_properties.csv"), dtype=str)
snap = pd.read_csv(os.path.join(P, "ahcp_snapshots.csv.gz"), dtype=str, parse_dates=["inspection_date"])
out, fails, S = [], [], {}


def h(t): out.append("\n" + t + "\n" + "-" * len(t))
def w(*a): out.append(" ".join(str(x) for x in a))
def check(name, ok, detail=""):
    w(("PASS" if ok else "FAIL"), name, detail)
    if not ok: fails.append(name)
def pct(a, b): return round(100.0 * a / b, 2) if b else float("nan")


out.append("AHCP v1.0 QA REPORT\n===================\nGenerated by code/04_qa.py from data/processed and data/interim.")

h("1. Row counts by stage")
w("Raw rows read, by source file:")
for k, v in bc["raw_rows_by_file"].items(): w(f"   {k:8s} {v:>8,}")
w(f"Raw rows total                     {bc['raw_rows']:>9,}")
w(f"Dropped: missing score/date/ID     {bc['raw_rows'] - bc['rows_after_required_fields']:>9,}")
w(f"Dropped: exact duplicates in file  {bc['within_file_duplicate_rows_dropped']:>9,}")
w(f"Snapshot rows (property x vintage) {len(snap):>9,}")
w(f"Unique inspections                 {len(insp):>9,}")
w(f"Properties                         {len(prop):>9,}")
check("snapshot rows equal raw rows minus drops", len(snap) == bc["raw_rows"] - (bc["raw_rows"] - bc["rows_after_required_fields"]) - bc["within_file_duplicate_rows_dropped"])
check("every snapshot row maps to an inspection", snap.ahcp_inspection_id.isin(insp.ahcp_inspection_id).all())
check("every inspection maps to a property", insp.ahcp_property_id.isin(prop.ahcp_property_id).all())
check("every property has at least one inspection", prop.n_inspections.notna().all() and (prop.n_inspections.astype(float) >= 1).all())

h("2. Key uniqueness")
check("ahcp_inspection_id unique", insp.ahcp_inspection_id.is_unique)
check("ahcp_property_id unique", prop.ahcp_property_id.is_unique)
check("one row per inspection per vintage in snapshots", not snap.duplicated(["ahcp_inspection_id", "vintage"]).any())
d2 = insp.duplicated(["ahcp_property_id", "inspection_date"], keep=False)
w(f"Inspections sharing a property and date with another inspection: {int(d2.sum())} (kept; distinct HUD inspection IDs)")

h("3. Range and sanity checks")
check("scores within 0-100", insp.inspection_score.between(0, 100).all(), f"min {insp.inspection_score.min()} max {insp.inspection_score.max()}")
check("inspection dates within 2000-01-01..2026-04-08", insp.inspection_date.between("2000-01-01", "2026-04-08").all(), f"{insp.inspection_date.min().date()} to {insp.inspection_date.max().date()}")
snap["vintage"] = snap.vintage.astype(int); snap["source_row"] = snap.source_row.astype(int); snap["inspection_score"] = snap.inspection_score.astype(float)
asof = snap.vintage.map({k: pd.Timestamp(v) for k, v in L.VINTAGES.items()})
late = snap[snap.inspection_date > asof]
w(f"Snapshot rows dated after their file's stated as-of date: {len(late)} ({late.vintage.value_counts().to_dict()})")
lat = pd.to_numeric(prop.latitude); lon = pd.to_numeric(prop.longitude)
check("coordinates within US bounds (incl. territories)", bool(lat.dropna().between(13, 72).all() and (lon.dropna().between(-180, -64) | lon.dropna().between(144, 146)).all()))
check("no protocol left undetermined", (insp.protocol != "UNKNOWN").all(), str(insp.protocol.value_counts().to_dict()))
nsp = insp[insp.protocol == "NSPIRE"]
for p_, start in (("PH", "2023-07-01"), ("MF", "2023-10-01")):
    e = nsp[(nsp.program == p_) & (nsp.inspection_date < start)]
    w(f"HUD-flagged NSPIRE {p_} inspections dated before {start}: {len(e)} (earliest {nsp[nsp.program == p_].inspection_date.min().date()})")
upl = insp[(insp.protocol == "UPCS") & (insp.protocol_source == "hud_flag")]
for p_, start in (("PH", "2023-07-01"), ("MF", "2023-10-01")):
    e = upl[(upl.program == p_) & (upl.inspection_date >= start)]
    w(f"HUD-flagged UPCS {p_} inspections dated on/after {start}: {len(e)}")
w("Protocol by source:", insp.groupby(["protocol", "protocol_source"]).size().to_dict())
w("Mean score by protocol:", insp.groupby("protocol").inspection_score.agg(["mean", "median", "count"]).round(2).to_dict("index"))

h("4. Cross-vintage reconciliation")
w(f"Inspections listed in more than one vintage: {int((insp.n_vintages > 1).sum()):,}")
w(f"  with a score that differs between vintages: {int(insp.score_conflict.sum())}")
w(f"  with a date that differs between vintages:  {int((insp.date_conflict_days != 0).sum())}  (by more than 1 day: {int((insp.date_conflict_days.abs() > 1).sum())})")
w(f"Inspection rows whose HUD inspection ID is shared by two properties (kept once per property): {int(insp.shared_inspection_id.sum())}")
w("  Rule applied: the most recent vintage's value is kept; min/max and flags retained.")
sc = insp[insp.score_conflict == 1]; w("  Score-conflict size (max-min): ", (sc.score_max_across_vintages - sc.score_min_across_vintages).describe().round(1).to_dict())

h("5. Coverage by inspection year (unique inspections)")
yr = insp.groupby(["inspection_year", "program"]).size().unstack(fill_value=0)
for y in range(2000, 2027):
    r = yr.loc[y] if y in yr.index else pd.Series({"MF": 0, "PH": 0})
    w(f"   {y}  MF {int(r.get('MF', 0)):>6,}  PH {int(r.get('PH', 0)):>6,}")
w("   NOTE: 2010-2012 are essentially absent from every file HUD still publishes; 2020-2021 reflect the pandemic pause.")
w("Inspections per property:", prop.n_inspections.astype(int).describe().round(2).to_dict())

h("6. Linkage match rates")
n = len(prop); tm = lc["tract_method"]
w(f"Tract (2020) assigned: {tm.get('contains', 0) + tm.get('nearest_vertex', 0):,} of {n:,} ({pct(tm.get('contains', 0) + tm.get('nearest_vertex', 0), n)}%)  {tm}")
w(f"  county implied by tract equals county in HUD file: {lc['tract_county_agree']:,} of {lc['tract_county_check_n']:,} ({pct(lc['tract_county_agree'], lc['tract_county_check_n'])}%)")
w(f"  disagreements by state (top): {lc['tract_county_disagree_by_state']}")
w(f"Subsidy layer: {lc['subsidy_layer']}")
for k, (a, b) in lc["subsidy_match_latest_vintage"].items(): w(f"  among properties in the 2026 vintage, {k}: {a:,} of {b:,} matched ({pct(a, b)}%)")
w(f"LIHTC link: {lc['lihtc_match_type']}")
w(f"  agreement with HUD's own tax-credit flag (multifamily layer): {lc['lihtc_vs_hud_flag']}")
w(f"PLACES tract health: {lc['places_property_match'][0]:,} of {lc['places_property_match'][1]:,} tract-coded properties matched ({pct(*lc['places_property_match'])}%); unmatched by state {lc['places_unmatched_by_state']}")
w(f"Pre-AMP public housing projects: {lc['legacy_projects']:,}; with any AMP candidate {lc['legacy_with_any_candidate']:,}; with exactly one {lc['legacy_with_unique_candidate']:,}")
check("tract/county agreement at least 99%", lc["tract_county_agree"] / lc["tract_county_check_n"] >= 0.99)
check("subsidy match among current MF properties at least 95%", lc["subsidy_match_latest_vintage"]["MF"][0] / lc["subsidy_match_latest_vintage"]["MF"][1] >= 0.95)
check("subsidy match among current PH properties at least 95%", lc["subsidy_match_latest_vintage"]["PH"][0] / lc["subsidy_match_latest_vintage"]["PH"][1] >= 0.95)

h("7. Independent round-trip check against the 2026 workbooks")
for prog in ("ph", "mf"):
    ws = openpyxl.load_workbook(os.path.join(L.RAW, f"ahcp_{prog}_2026.xlsx"), read_only=True).worksheets[0]
    rows = ws.iter_rows(values_only=True); hdr = [str(c).strip().upper() if c else "" for c in next(rows)]
    ii, si = hdr.index("INSPECTION_ID"), hdr.index("INSPECTION_SCORE")
    src = {f"{prog.upper()}:{str(r[ii]).strip()}": float(r[si]) for r in rows if r[ii] is not None}
    got = insp[insp.ahcp_inspection_id.isin(src)].set_index("ahcp_inspection_id").inspection_score
    ok = len(got) == len(src) and all(abs(got[k] - v) < 1e-9 for k, v in src.items())
    check(f"{prog.upper()} 2026: all {len(src):,} source inspections present with identical score", ok)

h("8. Named spot checks (verify each line by hand against the source file and row shown)")
def show(pid, why):
    w(f"\n[{why}] {pid}  {prop.set_index('ahcp_property_id').loc[pid, ['property_name', 'city', 'state_abbr']].tolist()}")
    for r in snap[snap.ahcp_property_id == pid].sort_values(["inspection_date", "vintage"]).itertuples():
        w(f"   {r.source_file:18s} row {r.source_row:>6}  insp {str(r.inspection_id):>10}  {r.inspection_date.date()}  score {r.inspection_score:g}  {r.protocol_hud if isinstance(r.protocol_hud, str) else ''}")
pi = prop.set_index("ahcp_property_id")
picks = [("MF:800006929", "easy case: multifamily property listed in many vintages")]
both = prop[(prop.has_both_protocols == "1") & (prop.program == "PH")].ahcp_property_id
if len(both): picks.append((sorted(both)[0], "public housing with UPCS and NSPIRE inspections"))
cf = insp[insp.score_conflict == 1].sort_values("ahcp_inspection_id").ahcp_property_id
if len(cf): picks.append((cf.iloc[0], "hard case: score differs between vintages"))
lo = insp[(insp.last_vintage == 2026) & (insp.protocol == "NSPIRE")].sort_values(["inspection_score", "ahcp_inspection_id"]).ahcp_property_id
if len(lo): picks.append((lo.iloc[0], "extreme: lowest NSPIRE score in the 2026 vintage"))
lg = prop[prop.amp_candidate_id.notna()].sort_values("ahcp_property_id")
if len(lg): picks.append((lg.ahcp_property_id.iloc[0], f"pre-AMP project with candidate crosswalk to {lg.amp_candidate_id.iloc[0]}"))
ct = prop[(prop.state_abbr == "CT") & (prop.city.str.upper() == "HARTFORD") & (prop.in_latest_vintage == "1")].sort_values("ahcp_property_id")
if len(ct): picks.append((ct.ahcp_property_id.iloc[0], "Hartford, CT property (tract re-keyed for PLACES)"))
for pid, why in picks: show(pid, why)
S["spot_checks"] = [p for p, _ in picks]

h("RESULT")
w("ALL HARD CHECKS PASSED" if not fails else "FAILED: " + "; ".join(fails))
open(os.path.join(P, "qa_report.txt"), "w").write("\n".join(out) + "\n")

# ---- stats file -------------------------------------------------------------------------------------------
ps = insp.groupby(["protocol", "protocol_source"]).size()
S.update({
    "version": "1.0", "vintages": sorted(L.VINTAGES), "n_vintages": len(L.VINTAGES), "raw_rows": bc["raw_rows"], "snapshot_rows": int(len(snap)),
    "inspections": int(len(insp)), "inspections_mf": int((insp.program == "MF").sum()), "inspections_ph": int((insp.program == "PH").sum()),
    "properties": int(len(prop)), "properties_mf": int((prop.program == "MF").sum()), "properties_ph": int((prop.program == "PH").sum()),
    "properties_ph_amp": int((prop.id_scheme == "PIC_AMP_DEVELOPMENT").sum()), "properties_ph_pre_amp": int((prop.id_scheme == "PIC_PRE_AMP_PROJECT").sum()),
    "first_inspection_date": str(insp.inspection_date.min().date()), "last_inspection_date": str(insp.inspection_date.max().date()),
    "nspire_hud_flag": int(ps.get(("NSPIRE", "hud_flag"), 0)), "upcs_hud_flag": int(ps.get(("UPCS", "hud_flag"), 0)),
    "upcs_inferred": int(ps.get(("UPCS", "inferred_pre_nspire_date"), 0)), "nspire_inferred": int(ps.get(("NSPIRE", "inferred_id_prefix"), 0)),
    "properties_both_protocols": int((prop.has_both_protocols == "1").sum()),
    "score_conflicts": int(insp.score_conflict.sum()), "date_conflicts": int((insp.date_conflict_days != 0).sum()),
    "date_conflicts_over_1_day": int((insp.date_conflict_days.abs() > 1).sum()),
    "inspections_2010_2012": int(insp.inspection_year.between(2010, 2012).sum()),
    "properties_multi_inspection": int((prop.n_inspections.astype(int) > 1).sum()), "median_inspections_per_property": float(prop.n_inspections.astype(int).median()),
    "tract_assigned": int(prop.tract_geoid_2020.notna().sum()), "tract_assigned_pct": pct(prop.tract_geoid_2020.notna().sum(), n),
    "properties_no_coordinates": int(tm.get("no_coordinates", 0)), "tract_county_agree_pct": pct(lc["tract_county_agree"], lc["tract_county_check_n"]),
    "subsidy_linked": int((prop.hud_layer != "not_in_current_hud_layers").sum()),
    "subsidy_linked_current_mf_pct": pct(*lc["subsidy_match_latest_vintage"]["MF"]), "subsidy_linked_current_ph_pct": pct(*lc["subsidy_match_latest_vintage"]["PH"]),
    "lihtc_linked": int((prop.lihtc_match_type != "none").sum()), "lihtc_linked_address": int((prop.lihtc_match_type == "address_zip").sum()),
    "lihtc_linked_proximity": int((prop.lihtc_match_type == "proximity_house_number").sum()),
    "lihtc_flag_y_linked_pct": pct(lc["lihtc_vs_hud_flag"]["Y"]["linked"], lc["lihtc_vs_hud_flag"]["Y"]["linked"] + lc["lihtc_vs_hud_flag"]["Y"]["not_linked"]),
    "lihtc_flag_n_linked_pct": pct(lc["lihtc_vs_hud_flag"]["N"]["linked"], lc["lihtc_vs_hud_flag"]["N"]["linked"] + lc["lihtc_vs_hud_flag"]["N"]["not_linked"]),
    "places_matched": lc["places_property_match"][0], "places_matched_pct": pct(*lc["places_property_match"]), "places_tracts": lc["places_tracts_used"],
    "legacy_unique_candidate": lc["legacy_with_unique_candidate"], "legacy_any_candidate": lc["legacy_with_any_candidate"],
    "nspire_mf_before_start": int(((nsp.program == "MF") & (nsp.inspection_date < "2023-10-01")).sum()),
    "property_columns": len(prop.columns), "inspection_columns": len(insp.columns), "qa_hard_fails": len(fails),
})
json.dump(S, open(os.path.join(ROOT, "paper", "stats.json"), "w"), indent=1)
print("\n".join(out)); sys.exit(1 if fails else 0)
